### PR TITLE
Metadata update

### PR DESCRIPTION
**Pull request by DougManuel**
See the changelog for updates. 

Addresses #2 and #3.

- Assay method database added
- change test results to be represented as key:values. Each test result has a measurement type (`measureType`) with a corresponding value (`measureValue`). For example a measureType is `mean` and the corresponding `measureValue` has the mean value.

### CODE REVIEW

**Review by hswerdfe — COMMENTED** [review]
Maybe this would be easier to talk about in person, I feel like somehow there are an excessive number of many to many relationships.

**Review by wyusuf068 — COMMENTED** [review]
I agree with @hswerdfe. The diagram does appear to be a bit tricky to follow.

**Comment by DougManuel** [comment]
> I agree with @hswerdfe. The diagram does appear to be a bit tricky to follow.

I agree as well. Many of those arrows are edge cases. I'll roll back to what I had previously. We can always add the arrows back if we actually do use this flow diagram to make an SQL database or similar. (You can actually export the ERD as SQL code.)

**Comment by DougManuel** [comment]
There are a few categories in `siteType` and other variables that have space characters and are a bit long. The categories become variables in a few collection tools and also flat databases. I wonder about making them more concise and without spaces. 

i.e. `sewer access point - flowing water` becomes `sewer-access-point_flowing-water` or `sap_flowing-water`, with a descriptive category label.

**Comment by hswerdfe** [comment]
@DougManuel good point, I agree.

**Comment by DougManuel** [comment]
@hswerdfe I went for it! 

I updated all variables and categories to be consistent camelCase. at the end metadata.md  I made an example of how to make wide data from long data to address https://github.com/Big-Life-Lab/covid-19-wastewater/issues/7#issuecomment-727626220.

I haven't updated the ERD but will if these suggestions look good.

**Review by wyusuf068 — APPROVED** [review]
Looks very good.

**Review by hswerdfe — APPROVED** [review]

**Pull request merged**
