### PR TITLE
auto generation of meta data files, note the _fr template should real…

### PR DESCRIPTION
**Pull request by hswerdfe**
should be checked by a french speaker... everything was done with deepl.com

### CODE REVIEW

**Comment by hswerdfe** [comment]
especially we should check the file metadata_template_fr.md

**Comment by DougManuel** [comment]
Just two small comments:
1) We could remove reference to lucidchart ERD, now that we are generating the ERD.
2) "FOR_REPLACE_LIST_OF_TABLES_DETAILS" was in the final metadata_fr.md file.

**Comment by hswerdfe** [comment]
thanks @DougManuel those two issues are fixed now

**Comment by hswerdfe** [comment]
addresses #106

**Comment by jeandavidt** [comment]
I'm having trouble installing the packages needed to run the code in this PR. @hswerdfe could you give some info on your environment like the R version and os you're using?

Also, when I try to install datamodelr, the install.packages command tells me there is no version of the package is available for my version of R (i tried with both 3.6.3 and 4.0.4, no dice). Could you let me know how / where you installed it from? Thanks!

**Comment by hswerdfe** [comment]
```
> print(sessionInfo())
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] htmltools_0.5.1.1     datamodelr_0.2.2.9002 DiagrammeRsvg_0.1    
 [4] DiagrammeR_1.0.6.1    magrittr_2.0.1        glue_1.4.2           
 [7] RSQLite_2.2.3         DBI_1.1.1             forcats_0.5.1        
[10] stringr_1.4.0         dplyr_1.0.4           purrr_0.3.4          
[13] readr_1.4.0           tidyr_1.1.2           tibble_3.0.6         
[16] ggplot2_3.3.3         tidyverse_1.3.0      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         lubridate_1.7.9.2  visNetwork_2.0.9  
 [4] assertthat_0.2.1   digest_0.6.27      utf8_1.1.4        
 [7] V8_3.4.0           R6_2.5.0           cellranger_1.1.0  
[10] backports_1.2.1    reprex_1.0.0       httr_1.4.2        
[13] pillar_1.5.0       rlang_0.4.10       curl_4.3          
[16] readxl_1.3.1       rstudioapi_0.13    blob_1.2.1        
[19] RPostgres_1.3.1    htmlwidgets_1.5.3  bit_4.0.4         
[22] munsell_0.5.0      tinytex_0.29       broom_0.7.5       
[25] compiler_4.0.4     modelr_0.1.8       xfun_0.21         
[28] pkgconfig_2.0.3    tidyselect_1.1.0   fansi_0.4.2       
[31] crayon_1.4.1       dbplyr_2.1.0       withr_2.4.1       
[34] grid_4.0.4         jsonlite_1.7.2     gtable_0.3.0      
[37] lifecycle_1.0.0    scales_1.1.1       cli_2.3.0         
[40] stringi_1.5.3      cachem_1.0.3       fs_1.5.0          
[43] xml2_1.3.2         ellipsis_0.3.1     generics_0.1.0    
[46] vctrs_0.3.6        RColorBrewer_1.1-2 tools_4.0.4       
[49] bit64_4.0.5        hms_1.0.0          fastmap_1.1.0     
[52] colorspace_2.0-0   rvest_0.3.6        memoise_2.0.0     
[55] haven_2.3.1       
> print(version)
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.4                         
year           2021                        
month          02                          
day            15                          
svn rev        80002                       
language       R                           
version.string R version 4.0.4 (2021-02-15)
nickname       Lost Library Book 
```

**Comment by hswerdfe** [comment]
one thing to note is that `datamodelr` is not on cran and needs to be installed via `remotes` or `devtools` packages. devtools gives me problems on my machine so I used remotes.

**Comment by hswerdfe** [comment]
@jeandavidt this is the code I used to install `remotes::install_github("bergant/datamodelr")`

**Comment by hswerdfe** [comment]
@jeandavidt one more thing while I am thinking about it.
worry about and try to run the code in `generate_db_generations_sql.R` for the purposes of this commit, and its generated `sql` files. the rest of the code did work but was not maintained as the database structure evolved.

**Comment by jeandavidt** [comment]
> one thing to note is that `datamodelr` is not on cran and needs to be installed via `remotes` or `devtools` packages. devtools gives me problems on my machine so I used remotes. 

Great, that fixed my issue! Thank so much! ^^

**Review by jeandavidt — CHANGES_REQUESTED** [review]
`generate_db_generations_sq;.R` fails for me when trying to parse the description of the first variable of the Sample Table (the first table the functions generates).

At time of crashing, the variable `sql_str = "CREATE TABLE IF NOT EXISTS [Sample] (\n/*L'échantillon est un volume d'eau usée représentatif de l'eau présente sur un site, qui est ensuite analysé en laboratoire.*/\n\t[sampleID] char NOT NULL PRIMARY KEY, --Identifiant unique pour l'"`

Maybe it's an accent parsing problem?

**Comment by hswerdfe** [comment]
@jeandavidt I don't think it is a parsing problem with accents as the SQL code are all in english.
the only functional difference between the en and fr files is the comment is drawn from the english or french description.

**Comment by jeandavidt** [comment]
@hswerdfe Yes, it only crashes when building the french sql.
I suggested it might be because of the accents because the string in `sql_str` ends just before an accent

**Comment by hswerdfe** [comment]
@jeandavidt  `wbe_create_db_from_script(lang = "fr"))` I ran this line from R which loads in the french sql file and executes it, and everything worked fine? maybe it has something to do with encodings. I was trying to be careful with accents using "utf-8" in all cases.
not sure what is going on.

**Comment by DougManuel** [comment]
@jeandavidt to review and then merge.

**Review by jeandavidt — APPROVED** [review]
The french looks ok to me!

**Pull request merged**
